context: {}

package:
  name: ollama
  version: 0.3.3

source:
- url: https://files.pythonhosted.org/packages/a6/8e/60a9b065eb796ef3996451cbe2d8044f6b030696166693b9805ae33b8b4c/ollama-0.3.3.tar.gz
  sha256: f90a6d61803117f40b0e8ff17465cab5e1eb24758a473cfe8101aff38bc13b51

build:
  script: python -m pip install .

requirements:
  host:
  - poetry-core
  - python >=3.8, <4.0
  - pip
  run:
  - python >=3.8, <4.0
  - httpx >=0.27.0, <0.28.0

tests: []

about:
  homepage: https://ollama.ai
  summary: The official Python client for Ollama.
  license: MIT


