{% set name = "langchain-ollama" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_ollama-{{ version }}.tar.gz
  sha256: 250ad9f3edce1a0ca16e4fad19f783ac728d7d76888ba952c462cd9f680353f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9,<4.0
    - ollama >=0.3.0,<1
    - langchain-core >=0.3.0,<0.4.0

test:
  imports:
    - langchain_ollama
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Ollama and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - benmoss
