context: {}

package:
  name: langchain-ollama
  version: 0.2.0

source:
- url: https://files.pythonhosted.org/packages/81/1b/c05811f5a0bb0c57a4aadd01eaadbfff8cb0d1225a22e4a79d9185b984a2/langchain_ollama-0.2.0.tar.gz
  sha256: 250ad9f3edce1a0ca16e4fad19f783ac728d7d76888ba952c462cd9f680353f7

build:
  script: python -m pip install .

requirements:
  host:
  - poetry-core >=1.0.0
  - python >=3.9, <4.0
  - pip
  run:
  - python >=3.9, <4.0
  - langchain-core >=0.3.0, <0.4.0
  - ollama >=0.3.0, <1

tests: []

about:
  homepage: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Ollama and LangChain
  license: MIT


